// <auto-generated />
using System;
using CleanTenant.Infrastructure.Persistence.Main;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanTenant.Infrastructure.Persistence.Main.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260522053353_AddBuildingSchemaRefactor")]
    partial class AddBuildingSchemaRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.AccountCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AccountClass")
                        .HasColumnType("smallint")
                        .HasColumnName("account_class");

                    b.Property<short>("AccountType")
                        .HasColumnType("smallint")
                        .HasColumnName("account_type");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDetail")
                        .HasColumnType("boolean")
                        .HasColumnName("is_detail");

                    b.Property<bool>("IsMonetary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monetary");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("parent_code");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<string>("TemplateCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("template_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_account_codes");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_account_codes_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_account_codes_tenant_id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_account_codes_company_code")
                        .HasFilter("is_deleted = false");

                    b.ToTable("account_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_code_format", "code ~ '^[1-9][0-9]{2}(\\.[0-9]{2}(\\.[0-9]{3})?)?$'");

                            t.HasCheckConstraint("ck_account_code_level_match", "(level = 0 AND char_length(replace(code, '.', '')) = 3) OR (level = 1 AND char_length(replace(code, '.', '')) = 6) OR (level = 2 AND char_length(replace(code, '.', '')) = 9)");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_accounting_periods");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_accounting_periods_company_id");

                    b.HasIndex("FiscalYearId")
                        .HasDatabaseName("ix_accounting_periods_fiscal_year_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_accounting_periods_tenant_id");

                    b.HasIndex("CompanyId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_accounting_periods_company_year_month")
                        .HasFilter("is_deleted = false");

                    b.ToTable("accounting_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounting_period_dates", "end_date > start_date");

                            t.HasCheckConstraint("ck_accounting_period_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.AccountingSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("EDefterEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("e_defter_enabled");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_activated");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("RequireApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("require_approval");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<short>("VatPeriod")
                        .HasColumnType("smallint")
                        .HasColumnName("vat_period");

                    b.HasKey("Id")
                        .HasName("pk_accounting_settings");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounting_settings_company")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_accounting_settings_tenant_id");

                    b.ToTable("accounting_settings", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_code_id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<short>("AccountType")
                        .HasColumnType("smallint")
                        .HasColumnName("account_type");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("branch_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Iban")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("iban");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_accounting_bank_accounts");

                    b.HasIndex("AccountCodeId")
                        .HasDatabaseName("ix_accounting_bank_accounts_account_code_id")
                        .HasFilter("account_code_id IS NOT NULL");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_accounting_bank_accounts_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_accounting_bank_accounts_tenant_id");

                    b.ToTable("accounting_bank_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_bank_iban_format", "iban IS NULL OR iban ~ '^TR[0-9]{24}$'");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_code_id");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("accounting_period_id");

                    b.Property<decimal>("BudgetedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("budgeted_amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("AccountCodeId")
                        .HasDatabaseName("ix_budgets_account_code_id");

                    b.HasIndex("AccountingPeriodId")
                        .HasDatabaseName("ix_budgets_accounting_period_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_budgets_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_budgets_tenant_id");

                    b.HasIndex("CompanyId", "AccountingPeriodId", "AccountCodeId", "CostCenterId")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_company_period_account_costcenter")
                        .HasFilter("is_deleted = false");

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_amount", "budgeted_amount >= 0");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_cost_centers");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_cost_centers_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cost_centers_tenant_id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_centers_company_code")
                        .HasFilter("is_deleted = false");

                    b.ToTable("cost_centers", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.EntrySequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<short>("EntryType")
                        .HasColumnType("smallint")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_entry_sequences");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_entry_sequences_company_id");

                    b.HasIndex("FiscalYearId")
                        .HasDatabaseName("ix_entry_sequences_fiscal_year_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_entry_sequences_tenant_id");

                    b.HasIndex("CompanyId", "FiscalYearId", "EntryType")
                        .IsUnique()
                        .HasDatabaseName("ix_entry_sequences_company_year_type");

                    b.ToTable("entry_sequences", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrentYear")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_year");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_years");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_fiscal_years_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_fiscal_years_tenant_id");

                    b.HasIndex("CompanyId", "StartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_years_company_start")
                        .HasFilter("is_deleted = false");

                    b.ToTable("fiscal_years", null, t =>
                        {
                            t.HasCheckConstraint("ck_fiscal_year_dates", "end_date > start_date");

                            t.HasCheckConstraint("ck_fiscal_year_duration", "end_date - start_date BETWEEN 330 AND 400");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_code_id");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("accounting_period_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CounterpartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("counterparty_name");

                    b.Property<string>("CounterpartyTaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("counterparty_tax_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPostedToJournal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_posted_to_journal");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sub_total");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("vat_amount");

                    b.Property<short>("VatCategory")
                        .HasColumnType("smallint")
                        .HasColumnName("vat_category");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("AccountCodeId")
                        .HasDatabaseName("ix_invoices_account_code_id");

                    b.HasIndex("AccountingPeriodId")
                        .HasDatabaseName("ix_invoices_accounting_period_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_invoices_company_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_invoices_journal_entry_id")
                        .HasFilter("journal_entry_id IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_invoices_tenant_id");

                    b.HasIndex("CompanyId", "InvoiceNumber", "Direction")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_company_number_direction")
                        .HasFilter("is_deleted = false");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_amounts", "sub_total >= 0 AND vat_amount >= 0 AND total_amount = sub_total + vat_amount");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("accounting_period_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EDefterXml")
                        .HasColumnType("text")
                        .HasColumnName("e_defter_xml");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entry_number");

                    b.Property<short>("EntryType")
                        .HasColumnType("smallint")
                        .HasColumnName("entry_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("OriginalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_entry_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_debit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("AccountingPeriodId")
                        .HasDatabaseName("ix_journal_entries_accounting_period_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_journal_entries_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_journal_entries_tenant_id");

                    b.HasIndex("CompanyId", "EntryNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_company_number");

                    b.ToTable("journal_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_balanced", "status != 2 OR total_debit = total_credit");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_code_id");

                    b.Property<string>("AccountCodeValue")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("account_code_value");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("debit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<decimal?>("OriginalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("original_amount");

                    b.Property<string>("OriginalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("original_currency");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("AccountCodeId")
                        .HasDatabaseName("ix_journal_lines_account_code_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_journal_lines_company_id");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_journal_lines_cost_center_id")
                        .HasFilter("cost_center_id IS NOT NULL");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journal_lines_journal_entry_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_journal_lines_tenant_id");

                    b.ToTable("journal_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_line_sign", "debit >= 0 AND credit >= 0 AND (debit = 0 OR credit = 0)");
                        });
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("url_code");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_blocks_building_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_blocks_tenant_id");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_url_code");

                    b.HasIndex("BuildingId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_building_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("blocks", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MunicipalNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("municipal_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcel_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("url_code");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("ix_buildings_parcel_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_buildings_tenant_id");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_url_code");

                    b.HasIndex("ParcelId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_parcel_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Land", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("url_code");

                    b.HasKey("Id")
                        .HasName("pk_lands");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_lands_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lands_tenant_id");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasDatabaseName("ix_lands_url_code");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lands_company_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("lands", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LandId")
                        .HasColumnType("uuid")
                        .HasColumnName("land_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("url_code");

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("LandId")
                        .HasDatabaseName("ix_parcels_land_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_parcels_tenant_id");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasDatabaseName("ix_parcels_url_code");

                    b.HasIndex("LandId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_parcels_land_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("parcels", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AllocatedArea")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("allocated_area");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<decimal>("GrossSquareMeters")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gross_square_meters");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("LandShare")
                        .HasColumnType("integer")
                        .HasColumnName("land_share");

                    b.Property<short>("Layout")
                        .HasColumnType("smallint")
                        .HasColumnName("layout");

                    b.Property<string>("NationalAddressCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_address_code");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<short>("Orientation")
                        .HasColumnType("smallint")
                        .HasColumnName("orientation");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer")
                        .HasColumnName("room_count");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("SquareMeters")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("square_meters");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("url_code");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("ix_units_block_id");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_units_building_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_units_tenant_id");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasDatabaseName("ix_units_url_code");

                    b.HasIndex("BlockId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_units_block_number")
                        .HasFilter("is_deleted = false AND block_id IS NOT NULL");

                    b.HasIndex("BuildingId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_units_building_number")
                        .HasFilter("is_deleted = false AND block_id IS NULL");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LegalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("url_code");

                    b.Property<string>("Vkn")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("vkn")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_companies_tenant_id");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_url_code");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tenant_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("companies", null, t =>
                        {
                            t.HasCheckConstraint("ck_company_vkn_format", "vkn IS NULL OR vkn ~ '^[0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("CleanTenant.Infrastructure.Persistence.Identifiers.UrlCodeRegistry", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(9)
                        .HasColumnType("character(9)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_type");

                    b.HasKey("Code")
                        .HasName("pk_url_code_registry");

                    b.HasIndex("OwnerType", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_url_code_registry_owner_type_owner_id");

                    b.ToTable("url_code_registry", (string)null);
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.AccountingPeriod", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.Accounting.FiscalYear", "FiscalYear")
                        .WithMany("Periods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounting_periods_fiscal_years_fiscal_year_id");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.JournalLine", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.Accounting.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Block", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.BuildingSchema.Building", "Building")
                        .WithMany("Blocks")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_buildings_building_id");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Building", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.BuildingSchema.Parcel", "Parcel")
                        .WithMany("Buildings")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_parcels_parcel_id");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Land", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.Companies.Company", "Company")
                        .WithMany("Lands")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lands_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Parcel", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.BuildingSchema.Land", "Land")
                        .WithMany("Parcels")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parcels_lands_land_id");

                    b.Navigation("Land");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Unit", b =>
                {
                    b.HasOne("CleanTenant.Domain.Tenant.BuildingSchema.Block", "Block")
                        .WithMany("Units")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_units_blocks_block_id");

                    b.HasOne("CleanTenant.Domain.Tenant.BuildingSchema.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_buildings_building_id");

                    b.Navigation("Block");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.FiscalYear", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Accounting.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Block", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Building", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Land", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.BuildingSchema.Parcel", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("CleanTenant.Domain.Tenant.Companies.Company", b =>
                {
                    b.Navigation("Lands");
                });
#pragma warning restore 612, 618
        }
    }
}
