namespace CleanTenant.Infrastructure.Persistence.Seeding;

/// <summary>
/// <para>
/// Lokalizasyon çevirilerinin statik kataloğu. Her satır bir Key + TR + EN üçlüsü.
/// EN değeri null ise <c>"[EN] {tr}"</c> placeholder oluşturulur ve
/// <c>IsMachineTranslated=true</c> işaretlenir — sistem yöneticisi
/// <c>/system/localization</c> sayfasında elle revize eder.
/// </para>
/// <para>
/// <b>Key naming:</b> Dot-notation, düz hiyerarşi (5. UI kararına göre).
/// Örn. <c>"User.Read.Description"</c>, <c>"Roles.New.SubmitButton"</c>.
/// </para>
/// </summary>
public static class LocalizationCatalog
{
    /// <summary>Tek bir çeviri kaydı.</summary>
    /// <param name="Key">Stabil dot-notation anahtarı.</param>
    /// <param name="Tr">Türkçe değer (kaynak).</param>
    /// <param name="En">İngilizce değer (null ise machine-stub üretilir).</param>
    public sealed record Definition(string Key, string Tr, string? En = null);

    /// <summary>Tüm çeviri kayıtları — yeni key ekleyince liste sonuna ekle.</summary>
    public static readonly IReadOnlyList<Definition> All =
    [
        // ========== Permission Module Names (Modul başlıkları) ==========
        new("Permission.Module.Identity",       "Kimlik & Yetki",       "Identity & Authorization"),
        new("Permission.Module.Tenant",         "Yönetim",              "Tenant"),
        new("Permission.Module.Company",        "Site",                 "Company"),
        new("Permission.Module.Site",           "Yapı Şeması",          "Building Schema"),
        new("Permission.Module.Billing",        "Faturalama",           "Billing"),
        new("Permission.Module.Audit",          "Denetim & Log",        "Audit & Log"),
        new("Permission.Module.Support",        "Destek Modu",          "Support Mode"),
        new("Permission.Module.Reporting",      "Raporlar",             "Reporting"),
        new("Permission.Module.System",         "Sistem",               "System"),
        new("Permission.Module.LookUp",         "Tanım Tabloları",      "Lookup Tables"),
        new("Permission.Module.CompanyParams",  "Site Parametreleri",   "Company Parameters"),

        // ========== Permission Descriptions (49) ==========
        // Identity
        new("Permission.User.Read",             "Kullanıcı kayıtlarını görüntüleme",     "View user records"),
        new("Permission.User.Create",           "Yeni kullanıcı oluşturma",              "Create new user"),
        new("Permission.User.Update",           "Kullanıcı bilgilerini güncelleme",      "Update user details"),
        new("Permission.User.Delete",           "Kullanıcı silme (soft)",                "Delete user (soft)"),
        new("Permission.User.Lockout",          "Kullanıcı kilitleme/açma",              "Lock/unlock user"),
        new("Permission.User.ResetPassword",    "Kullanıcı şifresi sıfırlama (sistem onayı)", "Reset user password (system)"),
        new("Permission.Role.Read",             "Rol tanımlarını görüntüleme",           "View role definitions"),
        new("Permission.Role.Create",           "Yeni rol oluşturma",                    "Create new role"),
        new("Permission.Role.Update",           "Rol güncelleme",                        "Update role"),
        new("Permission.Role.Delete",           "Rol silme",                             "Delete role"),
        new("Permission.Role.AssignPermissions","Role permission atama/kaldırma",        "Assign/unassign permissions to role"),
        new("Permission.Permission.Read",       "Permission kataloğunu görüntüleme",     "View permission catalog"),

        // Tenant
        new("Permission.Tenant.Read",           "Tenant kayıtlarını görüntüleme",        "View tenant records"),
        new("Permission.Tenant.Create",         "Yeni tenant onboarding",                "Tenant onboarding"),
        new("Permission.Tenant.Update",         "Tenant bilgilerini güncelleme",         "Update tenant details"),
        new("Permission.Tenant.Suspend",        "Tenant askıya alma",                    "Suspend tenant"),
        new("Permission.Tenant.Terminate",      "Tenant kapatma",                        "Terminate tenant"),

        // Company
        new("Permission.Company.Read",          "Şirket kayıtlarını görüntüleme",        "View company records"),
        new("Permission.Company.Create",        "Yeni şirket oluşturma",                 "Create new company"),
        new("Permission.Company.Update",        "Şirket güncelleme",                     "Update company"),
        new("Permission.Company.Delete",        "Şirket silme",                          "Delete company"),

        // Building Schema
        new("Permission.Building.Read",         "Bina/blok görüntüleme",                 "View building/block"),
        new("Permission.Building.Create",       "Bina/blok oluşturma",                   "Create building/block"),
        new("Permission.Building.Update",       "Bina/blok güncelleme",                  "Update building/block"),
        new("Permission.Building.Delete",       "Bina/blok silme",                       "Delete building/block"),
        new("Permission.Unit.Read",             "Bağımsız bölüm görüntüleme",            "View unit"),
        new("Permission.Unit.Create",           "Bağımsız bölüm oluşturma",              "Create unit"),
        new("Permission.Unit.Update",           "Bağımsız bölüm güncelleme",             "Update unit"),

        // Billing
        new("Permission.Invoice.Read",          "Fatura görüntüleme",                    "View invoice"),
        new("Permission.Invoice.Create",        "Fatura oluşturma",                      "Create invoice"),
        new("Permission.Invoice.Approve",       "Fatura onaylama",                       "Approve invoice"),
        new("Permission.Invoice.Cancel",        "Fatura iptali",                         "Cancel invoice"),
        new("Permission.Payment.Read",          "Ödeme görüntüleme",                     "View payment"),
        new("Permission.Payment.Refund",        "Ödeme iadesi",                          "Refund payment"),

        // Audit & Log
        new("Permission.Audit.Read.Tenant",     "Kendi tenant audit kayıtlarını görüntüleme", "View own tenant audit records"),
        new("Permission.Audit.Read.All",        "Tüm tenant'ların audit kayıtlarına erişim",  "Access all tenants' audit records"),
        new("Permission.Log.Read.Tenant",       "Kendi tenant loglarını görüntüleme",    "View own tenant logs"),
        new("Permission.Log.Read.All",          "Tüm log kayıtlarına erişim",            "Access all log records"),

        // Support Mode
        new("Permission.Support.EnterMode",      "Support Mode başlatma yetkisi",                       "Enter Support Mode"),
        new("Permission.Support.ElevateToWrite", "Support Mode'da yazma yetkisine yükselme",            "Elevate to write in Support Mode"),
        new("Permission.Support.Impersonate",    "Tenant kullanıcısı olarak görüntüleme (impersonation)", "View as tenant user (impersonation)"),
        new("Permission.Support.History.Tenant", "Tenant'ın destek erişim geçmişini görüntüleme",       "View tenant's support access history"),

        // Reporting
        new("Permission.Reporting.Tenant",      "Tenant raporları",                      "Tenant reports"),
        new("Permission.Reporting.Company",     "Şirket raporları",                      "Company reports"),
        new("Permission.Reporting.System",      "Sistem geneli raporlar",                "System-wide reports"),

        // System
        new("Permission.System.Settings.Manage",     "Sistem ayarlarını yönetme",        "Manage system settings"),
        new("Permission.System.Localization.Manage", "Dil kaynaklarını yönetme",         "Manage localization resources"),

        // LookUp
        new("Permission.LookUp.Read",   "LookUp tabloları (il, ilçe, mahalle, mesken tipi, yapı tipi, banka) görüntüleme",
                                        "View lookup tables (province, district, neighborhood, residential/building types, banks)"),
        new("Permission.LookUp.Manage", "LookUp tablolarını oluşturma, güncelleme ve silme",
                                        "Create, update and delete lookup tables"),

        // Company Detay Tab'ları
        new("Permission.company.info.read",        "Site bilgiler tab — okuma",       "Company info tab — read"),
        new("Permission.company.info.write",       "Site bilgiler tab — düzenleme",   "Company info tab — write"),
        new("Permission.company.contact.read",     "Site iletişim tab — okuma",       "Company contact tab — read"),
        new("Permission.company.contact.write",    "Site iletişim tab — düzenleme",   "Company contact tab — write"),
        new("Permission.company.accounting.read",  "Site muhasebe tab — okuma",       "Company accounting tab — read"),
        new("Permission.company.accounting.write", "Site muhasebe tab — düzenleme",   "Company accounting tab — write"),
        new("Permission.company.finance.read",     "Site finans tab — okuma",         "Company finance tab — read"),
        new("Permission.company.finance.write",    "Site finans tab — düzenleme",     "Company finance tab — write"),
        new("Permission.company.hr.read",          "Site İK tab — okuma",             "Company HR tab — read"),
        new("Permission.company.hr.write",         "Site İK tab — düzenleme",         "Company HR tab — write"),
        new("Permission.company.timesheet.read",   "Site puantaj tab — okuma",        "Company timesheet tab — read"),
        new("Permission.company.timesheet.write",  "Site puantaj tab — düzenleme",    "Company timesheet tab — write"),
        new("Permission.company.payroll.read",     "Site bordro tab — okuma",         "Company payroll tab — read"),
        new("Permission.company.payroll.write",    "Site bordro tab — düzenleme",     "Company payroll tab — write"),
        new("Permission.company.purchasing.read",  "Site satınalma tab — okuma",      "Company purchasing tab — read"),
        new("Permission.company.purchasing.write", "Site satınalma tab — düzenleme",  "Company purchasing tab — write"),

        // ========== Common Buttons & UI ==========
        new("Common.Save",          "Kaydet",       "Save"),
        new("Common.Cancel",        "İptal",        "Cancel"),
        new("Common.Delete",        "Sil",          "Delete"),
        new("Common.Edit",          "Düzenle",      "Edit"),
        new("Common.View",          "Görüntüle",    "View"),
        new("Common.New",           "Yeni",         "New"),
        new("Common.Search",        "Ara",          "Search"),
        new("Common.Filter",        "Filtrele",     "Filter"),
        new("Common.Loading",       "Yükleniyor…",  "Loading…"),
        new("Common.Saving",        "Kaydediliyor…","Saving…"),
        new("Common.Yes",           "Evet",         "Yes"),
        new("Common.No",            "Hayır",        "No"),
        new("Common.Confirm",       "Onayla",       "Confirm"),
        new("Common.Back",          "Geri",         "Back"),
        new("Common.Next",          "İleri",        "Next"),
        new("Common.SelectAll",     "Tümünü Seç",   "Select All"),
        new("Common.ClearAll",      "Tümünü Kaldır","Clear All"),
        new("Common.NotFound",      "Bulunamadı",   "Not Found"),
        new("Common.Unauthorized",  "Yetkisiz",     "Unauthorized"),
        new("Common.Error",         "Hata",         "Error"),

        // ========== Navigation Menu ==========
        new("Nav.Home",             "Anasayfa",          "Home"),
        new("Nav.Tenants",          "Yönetimler",        "Tenants"),
        new("Nav.Companies",        "Siteler",           "Companies"),
        new("Nav.Users",            "Kullanıcılar",      "Users"),
        new("Nav.Roles",            "Roller ve İzinler", "Roles & Permissions"),
        new("Nav.Audit",            "Denetim",           "Audit"),
        new("Nav.Settings",         "Ayarlar",           "Settings"),
        new("Nav.Profile",          "Profil",            "Profile"),
        new("Nav.SignOut",          "Çıkış",             "Sign Out"),
        new("Nav.Localization",     "Dil Kaynakları",    "Localization"),
        new("Nav.SystemArea",       "Sistem Alanı",      "System Area"),
        new("Nav.TenantArea",       "Yönetim Alanı",     "Tenant Area"),

        // ========== Roles List Page ==========
        new("Roles.List.Title",         "Roller",              "Roles"),
        new("Roles.List.ScopeFilter",   "Kapsam Seviyesi",     "Scope Level"),
        new("Roles.List.NewButton",     "Yeni Rol",            "New Role"),
        new("Roles.List.Search",        "Rol ara…",            "Search role…"),
        new("Roles.List.Col.Name",      "Rol Adı",             "Role Name"),
        new("Roles.List.Col.Description","Açıklama",           "Description"),
        new("Roles.List.Col.Scope",     "Kapsam",              "Scope"),
        new("Roles.List.Col.PermCount", "İzin Sayısı",         "Permission Count"),
        new("Roles.List.Col.BuiltIn",   "Built-in",            "Built-in"),
        new("Roles.List.Col.Source",    "Kaynak",              "Source"),
        new("Roles.List.Tag.BuiltIn",   "Sistem (Built-in)",   "System (Built-in)"),
        new("Roles.List.Tag.Global",    "Global",              "Global"),
        new("Roles.List.Tag.OwnTenant", "Bu Yönetim",          "This Tenant"),

        // ========== Role Edit/Create ==========
        new("Roles.Edit.Title",          "Rol Düzenle",                "Edit Role"),
        new("Roles.Edit.TitleReadOnly",  "Rol Görüntüle",              "View Role"),
        new("Roles.New.Title",           "Yeni Rol",                   "New Role"),
        new("Roles.Edit.PermissionsTitle","İzinler",                   "Permissions"),
        new("Roles.Edit.SaveButton",     "Değişiklikleri Kaydet",      "Save Changes"),
        new("Roles.Edit.SavePermsButton","İzinleri Kaydet",            "Save Permissions"),
        new("Roles.Edit.BuiltInBanner",  "Bu built-in roldür. İsmi ve açıklaması değiştirilemez; yalnız izinler güncellenebilir.",
                                         "This is a built-in role. Its name and description cannot be changed; only permissions can be updated."),
        new("Roles.Edit.ReadOnlyBanner", "Bu rol salt-okunur. Yalnız Sistem tarafından düzenlenebilir.",
                                         "This role is read-only. Only the System can edit it."),
        new("Roles.Form.Name",           "Rol Adı *",                  "Role Name *"),
        new("Roles.Form.Description",    "Açıklama",                   "Description"),
        new("Roles.Form.Scope",          "Kapsam Seviyesi *",          "Scope Level *"),

        // Scope dropdown values
        new("Scope.System",  "Sistem",   "System"),
        new("Scope.Tenant",  "Yönetim",  "Tenant"),
        new("Scope.Company", "Site",     "Company"),
        new("Scope.Unit",    "Birim",    "Unit"),

        // ========== Login Page ==========
        new("Login.Title",          "Giriş",                "Login"),
        new("Login.Email",          "E-posta",              "Email"),
        new("Login.Password",       "Şifre",                "Password"),
        new("Login.RememberMe",     "Beni Hatırla",         "Remember Me"),
        new("Login.SubmitButton",   "Giriş Yap",            "Sign In"),
        new("Login.ForgotPassword", "Şifremi Unuttum",      "Forgot Password"),

        // ========== Permission Picker ==========
        new("Permissions.Picker.NoResults",
            "Bu rol scope'una ve sizin yetkilerinize uyumlu atanabilir izin bulunamadı.",
            "No assignable permissions match this role's scope and your privileges."),
        new("Permissions.Picker.SelectAll",  "Tümünü Seç",     "Select All"),
        new("Permissions.Picker.ClearAll",   "Tümünü Kaldır",  "Clear All"),
        new("Permissions.Picker.Legend.Read",    "Okuma",    "Read"),
        new("Permissions.Picker.Legend.Create",  "Oluşturma","Create"),
        new("Permissions.Picker.Legend.Update",  "Güncelleme/Yazma/Yönetim", "Update / Write / Manage"),
        new("Permissions.Picker.Legend.Delete",  "Silme",    "Delete"),
        new("Permissions.Picker.Legend.Approve", "Onay",     "Approve"),
        new("Permissions.Picker.Legend.Other",   "Diğer",    "Other"),

        // ========== Culture Switcher ==========
        new("Culture.Switcher.Label",     "Dil",         "Language"),
        new("Culture.tr-TR",              "Türkçe",      "Turkish"),
        new("Culture.en-US",              "İngilizce",   "English"),
        new("Culture.ar-SA",              "Arapça",      "Arabic"),
        new("Culture.ru-RU",              "Rusça",       "Russian"),
        new("Culture.de-DE",              "Almanca",     "German"),

        // ========== Layout (MainLayout AppBar) ==========
        new("Layout.AppBar.Brand",           "Toplu Yapı Yönetimi", "Building Management"),
        new("Layout.AppBar.MenuToggle",      "Menüyü aç/kapa",      "Toggle menu"),
        new("Layout.AppBar.DarkMode",        "Koyu mod",            "Dark mode"),
        new("Layout.AppBar.LightMode",       "Açık mod",            "Light mode"),
        new("Layout.AppBar.ThemeSettings",   "Tema ayarları",       "Theme settings"),
        new("Layout.AppBar.Notifications",   "Bildirimler",         "Notifications"),
        new("Layout.AppBar.Language",        "Dil / Language",      "Language"),
        new("Layout.AppBar.Profile",         "Profilim",            "My Profile"),
        new("Layout.AppBar.TwoFactor",       "2FA Yönetimi",        "2FA Management"),
        new("Layout.AppBar.Settings",        "Ayarlar",             "Settings"),
        new("Layout.AppBar.SignOut",         "Çıkış",               "Sign Out"),
        new("Layout.Footer.Copyright",       "© 2026 CleanTenant",  "© 2026 CleanTenant"),
        new("Layout.Error.Unexpected",       "Beklenmedik bir hata oluştu.", "An unexpected error occurred."),
        new("Layout.Error.Reload",           "Yeniden yükle",       "Reload"),

        // ========== NavMenu ==========
        new("NavMenu.Search",                "Menüde ara…",         "Search menu…"),
        new("NavMenu.Dashboard",             "Dashboard",           "Dashboard"),
        new("NavMenu.Tenants",               "Yönetimler",          "Tenants"),
        new("NavMenu.Companies",             "Siteler",             "Companies"),
        new("NavMenu.Roles",                 "Roller",              "Roles"),
        new("NavMenu.RolesAndPermissions",   "Roller ve İzinler",   "Roles & Permissions"),
        new("NavMenu.LookUpTables",          "LookUp Tabloları",    "Lookup Tables"),
        new("NavMenu.Banks",                 "Bankalar",            "Banks"),
        new("NavMenu.AuditExplorer",         "Audit Explorer",      "Audit Explorer"),
        new("NavMenu.LogViewer",             "Log Görüntüleyici",   "Log Viewer"),
        new("NavMenu.PermissionCatalog",     "Permission Kataloğu", "Permission Catalog"),
        new("NavMenu.SystemSettings",        "Sistem Ayarları",     "System Settings"),
        new("NavMenu.SystemAdmin",           "Sistem Yönetimi",     "System Administration"),
        new("NavMenu.Users",                 "Kullanıcılar",        "Users"),
        new("NavMenu.AuditHistory",          "Audit Geçmişi",       "Audit History"),
        new("NavMenu.SupportAccess",         "Destek Erişim Geçmişi","Support Access History"),
        new("NavMenu.TenantSettings",        "Yönetim Ayarları",    "Tenant Settings"),
        new("NavMenu.Tenant",                "Yönetim",             "Tenant"),
        new("NavMenu.Units",                 "Birimler",            "Units"),
        new("NavMenu.Residents",             "Sakinler",            "Residents"),
        new("NavMenu.Invoices",              "Faturalar",           "Invoices"),
        new("NavMenu.CompanySettings",       "Site Ayarları",       "Company Settings"),
        new("NavMenu.Company",               "Site",                "Company"),
        new("NavMenu.Theme",                 "Tema",                "Theme"),
        new("NavMenu.Language",              "Dil",                 "Language"),
        new("NavMenu.About",                 "Hakkında",            "About"),
        new("NavMenu.Settings",              "Ayarlar",             "Settings"),

        // ========== DataTable Shared ==========
        new("DataTable.Total",               "Toplam: {0}",         "Total: {0}"),
        new("DataTable.ExcelDownload",       "Excel olarak indir",  "Download as Excel"),
        new("DataTable.PdfDownload",         "PDF olarak indir",    "Download as PDF"),
        new("DataTable.NoRecords",           "Kayıt bulunamadı",    "No records found"),
        new("DataTable.SearchPlaceholder",   "Ara…",                "Search…"),
        new("DataTable.DefaultTitle",        "Liste",               "List"),
        new("DataTable.Export.NoColumns.Excel","Excel export için kolon tanımı verilmedi.", "No column definitions provided for Excel export."),
        new("DataTable.Export.NoColumns.Pdf","PDF export için kolon tanımı verilmedi.", "No column definitions provided for PDF export."),

        // ========== Auth - Login ==========
        new("Login.Identifier",              "E-posta / TCKN / VKN / Telefon", "Email / TCKN / VKN / Phone"),
        new("Login.RememberMe.Days",         "Beni hatırla (7 gün)", "Remember me (7 days)"),
        new("Login.Footer",                  "CleanTenant Yönetim Paneli", "CleanTenant Management Panel"),
        new("Login.Error.IdentifierRequired","Kullanıcı kimliği ve şifre zorunlu.", "Username and password are required."),
        new("Login.Error.Invalid",           "Geçersiz kimlik veya şifre.", "Invalid identifier or password."),
        new("Login.Error.Lockout",           "Hesap geçici olarak kilitli (çok fazla başarısız deneme).", "Account temporarily locked (too many failed attempts)."),

        // ========== Auth - 2FA Challenge ==========
        new("TwoFactor.Challenge.Title",     "İki Faktörlü Doğrulama", "Two-Factor Authentication"),
        new("TwoFactor.Challenge.NoSession", "Aktif bir doğrulama oturumu bulunamadı. Giriş sayfasına dönün.",
                                             "No active verification session. Return to the login page."),
        new("TwoFactor.Challenge.BackToLogin","Giriş sayfasına dön", "Back to login page"),
        new("TwoFactor.Challenge.Prompt",    "Doğrulama yönteminizi seçin ve kodu girin.",
                                             "Choose your verification method and enter the code."),
        new("TwoFactor.Method.Label",        "Yöntem",              "Method"),
        new("TwoFactor.Method.Authenticator","Authenticator (TOTP)","Authenticator (TOTP)"),
        new("TwoFactor.Method.Email",        "E-posta kodu",        "Email code"),
        new("TwoFactor.Method.Sms",          "SMS kodu",            "SMS code"),
        new("TwoFactor.Method.Recovery",     "Recovery kodu",       "Recovery code"),
        new("TwoFactor.Code.SixDigit",       "6 haneli kod",        "6-digit code"),
        new("TwoFactor.Code.Recovery",       "Recovery kodu (XXXXX-XXXXX)", "Recovery code (XXXXX-XXXXX)"),
        new("TwoFactor.Verify",              "Doğrula",             "Verify"),
        new("TwoFactor.SendEmail",           "E-posta yöntemi için kod gönder", "Send code for email method"),
        new("TwoFactor.TokenValidity",       "Token 5 dakika geçerli.", "Token valid for 5 minutes."),
        new("TwoFactor.RestartLogin",        "Baştan giriş",        "Restart login"),
        new("TwoFactor.Error.MethodCodeRequired","Yöntem ve kod zorunlu.", "Method and code are required."),
        new("TwoFactor.Error.InvalidOrExpired","Doğrulama kodu hatalı veya süresi dolmuş.", "Verification code is invalid or expired."),

        // ========== Auth - 2FA Enrollment ==========
        new("TwoFactor.Enroll.Title",        "İki Faktörlü Doğrulama (TOTP)", "Two-Factor Authentication (TOTP)"),
        new("TwoFactor.Enroll.Intro",
            "Google Authenticator, Microsoft Authenticator veya benzer bir uygulamayla TOTP kurulumu yapın.",
            "Set up TOTP with Google Authenticator, Microsoft Authenticator, or a similar app."),
        new("TwoFactor.Enroll.Start",        "Enrollment başlat",   "Start enrollment"),
        new("TwoFactor.Enroll.Step1",        "1. Authenticator uygulamasını açın ve QR kodu tarayın",
                                             "1. Open your authenticator app and scan the QR code"),
        new("TwoFactor.Enroll.SecretHint",   "QR kodu tarayamıyorsanız bu secret'ı elle girebilirsiniz:",
                                             "If you can't scan the QR code, enter this secret manually:"),
        new("TwoFactor.Enroll.Step2",        "2. Authenticator uygulamasının verdiği 6 haneli kodu girin",
                                             "2. Enter the 6-digit code from your authenticator app"),
        new("TwoFactor.Enroll.Confirm",      "Onayla ve 2FA'yı Aktif Et", "Confirm and Activate 2FA"),
        new("TwoFactor.Enroll.Success",      "2FA aktif edildi! Aşağıdaki 10 recovery kodunu güvenli bir yere kaydedin.",
                                             "2FA activated! Save the 10 recovery codes below in a safe place."),
        new("TwoFactor.Enroll.DownloadCodes","Kurtarma kodlarını TXT olarak indir", "Download recovery codes as TXT"),
        new("TwoFactor.Enroll.AckCodes",     "Recovery kodlarını güvenli bir yere kaydettim.", "I've saved the recovery codes safely."),
        new("TwoFactor.Enroll.Done",         "Tamamla ve Dashboard'a Dön", "Complete and go to Dashboard"),

        // ========== NotFound (404) ==========
        new("NotFound.Title",                "Sayfa Bulunamadı",    "Page Not Found"),
        new("NotFound.Code",                 "404",                 "404"),
        new("NotFound.Message",              "Aradığınız sayfa mevcut değil veya silinmiş olabilir.",
                                             "The page you are looking for does not exist or may have been deleted."),
        new("NotFound.BackHome",             "Anasayfaya Dön",      "Back to Home"),

        // ========== Home / Dashboard ==========
        new("Home.Welcome",                  "Hoş geldiniz.",       "Welcome."),
        new("Home.Card.Tenants",             "Tenant Sayısı",       "Tenant Count"),
        new("Home.Card.ActiveUsers",         "Aktif Kullanıcı",     "Active Users"),
        new("Home.Card.ActiveSupport",       "Aktif Support",       "Active Support"),
        new("Home.Card.AuditToday",          "Bugünkü Audit",       "Today's Audit"),
        new("Home.Roadmap.Title",            "Faz 1 Yol Haritası",  "Phase 1 Roadmap"),
        new("Home.Breadcrumb",               "Anasayfa",            "Home"),

        // ========== About ==========
        new("About.Title",                   "Hakkında",            "About"),
        new("About.AppSection",              "Uygulama",            "Application"),
        new("About.Name",                    "Ad:",                 "Name:"),
        new("About.Version",                 "Sürüm:",              "Version:"),
        new("About.Phase",                   "Faz:",                "Phase:"),

        // ========== Settings Pages ==========
        new("Settings.Theme.Title",          "Tema Ayarları",       "Theme Settings"),
        new("Settings.Theme.Description",    "4 hazır tema preset'inden birini seçin. Tercihiniz tarayıcıda kalıcılaşır.",
                                             "Choose one of 4 ready-made theme presets. Your preference persists in the browser."),
        new("Settings.Theme.Legend",         "Primary · Secondary · AppBar", "Primary · Secondary · AppBar"),
        new("Settings.Theme.DarkActive",     "Koyu mod aktif",      "Dark mode active"),
        new("Settings.Theme.LightActive",    "Açık mod aktif",      "Light mode active"),
        new("Settings.Language.Title",       "Dil Ayarları",        "Language Settings"),

        // ========== System Area - Tenants List ==========
        new("Tenants.List.Title",            "Yönetimler",          "Tenants"),
        new("Tenants.List.UnauthorizedSystem","Bu sayfa yalnız Sistem kullanıcıları için. Aktif bağlamınız Sistem değil.",
                                             "This page is for System users only. Your active context is not System."),
        new("Tenants.List.Widget.TenantCount","Mevcut Yönetim Sayısı", "Current Tenant Count"),
        new("Tenants.List.Widget.CompanyCount","Mevcut Site Sayısı", "Current Company Count"),
        new("Tenants.List.Widget.UnitCount", "Mevcut Bağımsız Bölüm Sayısı", "Current Unit Count"),
        new("Tenants.List.NewButton",        "Yeni Yönetim",        "New Tenant"),
        new("Tenants.List.Search",           "Yönetim ara…",        "Search tenant…"),
        new("Tenants.List.Col.Name",         "Yönetim Adı",         "Tenant Name"),
        new("Tenants.List.Col.UrlCode",      "URL Kodu",            "URL Code"),
        new("Tenants.List.Col.LegalName",    "Yasal Ad",            "Legal Name"),
        new("Tenants.List.Col.Status",       "Durum",               "Status"),
        new("Tenants.List.Col.Tier",         "Katman",              "Tier"),
        new("Tenants.List.Col.SystemWrite",  "Sistem Yazma",        "System Write"),
        new("Tenants.List.Action.Switch",    "Bu Yönetim bağlamına geç", "Switch to this Tenant context"),
        new("Tenants.List.Delete.Title",     "Yönetim Sil",         "Delete Tenant"),
        new("Tenants.List.Delete.Confirm",   "{0} Yönetim'i silinecek (soft delete). Tüm kullanıcı rol atamaları pasif olur. Devam edilsin mi?",
                                             "Tenant '{0}' will be deleted (soft delete). All user role assignments will become inactive. Continue?"),
        new("Tenants.List.Delete.Cancel",    "Vazgeç",              "Cancel"),
        new("Tenants.List.Delete.Failed",    "Silme başarısız: {0}", "Deletion failed: {0}"),
        new("Tenants.List.Delete.Success",   "Yönetim silindi: {0}", "Tenant deleted: {0}"),

        // ========== System Area - Tenant Create/Edit ==========
        new("Tenants.New.Title",             "Yeni Yönetim",        "New Tenant"),
        new("Tenants.Edit.Title",            "Yönetim Düzenle",     "Edit Tenant"),
        new("Tenants.Edit.UrlCodeLabel",     "URL Kodu:",           "URL Code:"),
        new("Tenants.Edit.NotFound",         "Yönetim bulunamadı (URL Kodu: {0}).", "Tenant not found (URL Code: {0})."),
        new("Tenants.Edit.SubmitButton",     "Değişiklikleri Kaydet", "Save Changes"),
        new("Tenants.New.SubmitButton",      "Yönetim Oluştur",     "Create Tenant"),
        new("Tenants.Save.SettingsButton",   "Ayarları Kaydet",     "Save Settings"),
        new("Tenants.Save.Success",          "Yönetim oluşturuldu: {0}", "Tenant created: {0}"),
        new("Tenants.Save.UpdateSuccess",    "Yönetim güncellendi.", "Tenant updated."),
        new("Tenants.Settings.Title",        "Yönetim Ayarları",    "Tenant Settings"),
        new("Tenants.Settings.UnauthorizedTenant","Bu sayfa Yönetim Admin (TenantAdmin) için. Aktif bağlamınız Yönetim değil.",
                                             "This page is for Tenant Admin (TenantAdmin). Your active context is not Tenant."),
        new("Tenants.Settings.Caption",      "URL Kodu: {0} — kimlik bilgisi ve katman bilgisi yalnız sistem yöneticisi tarafından değiştirilebilir.",
                                             "URL Code: {0} — identity and tier info can only be changed by the system administrator."),

        // ========== Tenant Form ==========
        new("TenantForm.Section.Tenant",     "Yönetim Bilgileri",   "Tenant Information"),
        new("TenantForm.Name",               "Yönetim Adı *",       "Tenant Name *"),
        new("TenantForm.LegalName",          "Yasal Ad",            "Legal Name"),
        new("TenantForm.LegalIdentityType",  "Kimlik Tipi *",       "Identity Type *"),
        new("TenantForm.IdentityType.Vkn",   "VKN (Vergi Kimlik No)", "VKN (Tax ID)"),
        new("TenantForm.IdentityType.Tckn",  "TCKN",                "TCKN"),
        new("TenantForm.IdentityType.Ykn",   "YKN (Yabancı Kimlik No)", "YKN (Foreign ID)"),
        new("TenantForm.Address",            "Adres",               "Address"),
        new("TenantForm.BillingTier",        "Faturalama Katmanı *", "Billing Tier *"),
        new("TenantForm.Tier.Free",          "Free",                "Free"),
        new("TenantForm.Tier.Standard",      "Standard",            "Standard"),
        new("TenantForm.Tier.Enterprise",    "Enterprise",          "Enterprise"),
        new("TenantForm.DedicatedDb",        "Dedicated DB",        "Dedicated DB"),
        new("TenantForm.AllowSystemWrite",   "Sistem operatörünün yazma izni", "System operator write access"),
        new("TenantForm.AllowSystemWrite.Help",
            "Açık: Sistem destek kullanıcıları bu Yönetim'de yazma yapabilir. Kapalı: yalnız okuma.",
            "On: System support users can write in this Tenant. Off: read-only."),
        new("TenantForm.Section.Admin",      "Sorumlu Yönetici (TenantAdmin)", "Responsible Admin (TenantAdmin)"),
        new("TenantForm.Admin.Caption",
            "İlk admin kullanıcı otomatik oluşturulur. Welcome e-posta + şifre belirleme bağlantısı gönderilir.",
            "The initial admin user is created automatically. A welcome email + password setup link is sent."),
        new("TenantForm.Admin.FirstName",    "Ad *",                "First Name *"),
        new("TenantForm.Admin.LastName",     "Soyad *",             "Last Name *"),
        new("TenantForm.Admin.Email",        "E-posta *",           "Email *"),
        new("TenantForm.Admin.Phone",        "Cep Telefonu *",      "Mobile Phone *"),
        new("TenantForm.Admin.PhoneFormat",  "Format: 0(5XX) XXX-XX-XX", "Format: 0(5XX) XXX-XX-XX"),

        // ========== Tenant Form — Identity Number (mode-aware label/help) ==========
        new("TenantForm.IdentityNumber.Vkn",      "VKN *",                "VKN *"),
        new("TenantForm.IdentityNumber.Tckn",     "TCKN *",               "TCKN *"),
        new("TenantForm.IdentityNumber.Ykn",      "YKN *",                "YKN *"),
        new("TenantForm.IdentityNumber.Fallback", "Kimlik Numarası *",    "Identity Number *"),
        new("TenantForm.IdentityHelp.Vkn",         "10 haneli, ilk hane 1-9 arasında.", "10 digits, first digit 1-9."),
        new("TenantForm.IdentityHelp.Tckn",        "11 haneli, ilk hane 1-9 arasında.", "11 digits, first digit 1-9."),
        new("TenantForm.IdentityHelp.Ykn",         "11 haneli, '99' ile başlamalı.",    "11 digits, must start with '99'."),

        // ========== Role Form — Section ==========
        new("Roles.Form.Section.Info",       "Rol Bilgileri",        "Role Information"),

        // ========== System Area - Companies List ==========
        new("Companies.List.Title",          "Siteler",             "Companies"),
        new("Companies.List.UnauthorizedSystem","Bu sayfa yalnız Sistem kullanıcıları için.", "This page is for System users only."),
        new("Companies.List.NewButton",      "Yeni Site",           "New Company"),
        new("Companies.List.Search",         "Site / Yönetim ara…", "Search company / tenant…"),
        new("Companies.List.Col.Name",       "Site Adı",            "Company Name"),
        new("Companies.List.Col.UrlCode",    "URL Kodu",            "URL Code"),
        new("Companies.List.Col.Tenant",     "Yönetim",             "Tenant"),
        new("Companies.List.Col.LegalName",  "Yasal Ad",            "Legal Name"),
        new("Companies.List.Col.Status",     "Durum",               "Status"),
        new("Companies.List.Action.Switch",  "Bu Site bağlamına geç", "Switch to this Company context"),
        new("Companies.List.Action.BuildingSchema","Yapı Şeması",   "Building Schema"),
        new("Companies.List.Delete.Confirm", "Bu siteyi silmek istediğinizden emin misiniz?", "Are you sure you want to delete this company?"),

        // ========== Tenant Area - Companies List ==========
        new("Companies.TenantList.Title",    "Siteler — {0}",       "Companies — {0}"),
        new("Companies.TenantList.NoTenant", "Aktif Yönetim bağlamı yok. Önce bir Yönetim seçin.",
                                             "No active Tenant context. Choose a Tenant first."),
        new("Companies.TenantList.Search",   "Site ara…",           "Search company…"),

        // ========== Company Create/Edit ==========
        new("Companies.New.Title",           "Yeni Site",           "New Company"),
        new("Companies.New.TenantPicker",    "Yönetim (Tenant)",    "Tenant"),
        new("Companies.New.TenantPicker.Help","Bu sitenin bağlı olacağı yönetimi seçin", "Select the tenant this company will belong to"),
        new("Companies.New.SubmitButton",    "Oluştur",             "Create"),
        new("Companies.New.SelectTenant",    "Lütfen bir yönetim seçin.", "Please select a tenant."),
        new("Companies.Edit.Title",          "Site Düzenle",        "Edit Company"),
        new("Companies.Edit.NotFound",       "Site bulunamadı.",    "Company not found."),

        // ========== Company Form ==========
        new("CompanyForm.Section.Info",      "Site Bilgileri",      "Company Information"),
        new("CompanyForm.Name",              "Site Adı *",          "Company Name *"),
        new("CompanyForm.LegalName",         "Yasal Ad",            "Legal Name"),
        new("CompanyForm.Vkn",               "VKN",                 "VKN"),
        new("CompanyForm.Vkn.Help",          "10 haneli, ilk hane 1-9 arasında", "10 digits, first digit 1-9"),
        new("CompanyForm.Email",             "E-posta",             "Email"),
        new("CompanyForm.Phone",             "Telefon",             "Phone"),

        // ========== Company Detail Tabs ==========
        new("CompanyTabs.Info",              "Bilgiler",            "Information"),
        new("CompanyTabs.Contact",           "İletişim",            "Contact"),
        new("CompanyTabs.Accounting",        "Muhasebe",            "Accounting"),
        new("CompanyTabs.Finance",           "Finans",              "Finance"),
        new("CompanyTabs.Hr",                "İK",                  "HR"),
        new("CompanyTabs.Timesheet",         "Puantaj",             "Timesheet"),
        new("CompanyTabs.Payroll",           "Bordro",              "Payroll"),
        new("CompanyTabs.Purchasing",        "Satınalma",           "Purchasing"),
        new("CompanyTabs.Save.Success",      "Site bilgileri kaydedildi.", "Company information saved."),
        new("CompanyTabs.Placeholder.NotDefined", "{0} parametreleri henüz tanımlanmadı.", "{0} parameters are not yet defined."),
        new("CompanyTabs.Placeholder.Info",
            "Bu site için {0} modülüne özel parametre alanları ileriki fazlarda eklenecek.",
            "Parameter fields specific to the {0} module for this company will be added in future phases."),

        // ========== System Roles List (additional keys) ==========
        new("Roles.List.UnauthorizedSystem", "Bu sayfa yalnız Sistem kullanıcıları için. Aktif bağlamınız Sistem değil.",
                                             "This page is for System users only. Your active context is not System."),
        new("Roles.List.LoadError",          "Roller yüklenirken hata: {0}", "Error loading roles: {0}"),
        new("Roles.List.DeleteConfirm",      "'{0}' rolü silinecek. Devam etmek istiyor musunuz?", "Role '{0}' will be deleted. Continue?"),
        new("Roles.List.DeleteSuccess",      "Rol başarıyla silindi.", "Role deleted successfully."),

        // ========== Tenant Roles List ==========
        new("Roles.TenantList.Unauthorized", "Bu sayfa yalnız aktif bir Yönetim (Tenant) bağlamı olan kullanıcılar içindir.",
                                             "This page is for users with an active Tenant context."),
        new("Roles.TenantList.Action.ViewReadOnly", "Görüntüle (salt-okunur)", "View (read-only)"),

        // ========== Tenant Roles New ==========
        new("Roles.TenantNew.Info",
            "Yeni rol bu Yönetim'e özel olarak oluşturulur. Sadece bu Yönetim'in yöneticileri görür ve düzenleyebilir.",
            "The new role is created specifically for this Tenant. Only this Tenant's admins can see and edit it."),

        // ========== Role Edit (additional) ==========
        new("Roles.New.SubmitButton",        "Rol Oluştur",         "Create Role"),
        new("Roles.New.Success",             "Rol başarıyla oluşturuldu.", "Role created successfully."),
        new("Roles.Edit.UpdateSuccess",      "Rol başarıyla güncellendi.", "Role updated successfully."),
        new("Roles.Edit.SavePerms.Success",  "İzinler başarıyla kaydedildi.", "Permissions saved successfully."),
        new("Roles.Edit.LoadError",          "Rol yüklenirken hata: {0}", "Error loading role: {0}"),
        new("Roles.Edit.PermsLoadError",     "İzinler yüklenirken hata: {0}", "Error loading permissions: {0}"),
        new("Roles.Edit.NotFound",           "Rol bulunamadı.",     "Role not found."),

        // ========== Permission Picker tooltip ==========
        new("Permissions.Picker.MinScope",   "Gerekli scope: en az {0}", "Required scope: at least {0}"),

        // ========== Audit Explorer ==========
        new("Audit.Title",                   "Audit Explorer",      "Audit Explorer"),
        new("Audit.UnauthorizedSystem",      "Bu sayfa yalnız Sistem kullanıcıları için.", "This page is for System users only."),
        new("Audit.Filter.Title",            "Filtreler",           "Filters"),
        new("Audit.Filter.DateFrom",         "Başlangıç Tarihi",    "From Date"),
        new("Audit.Filter.DateTo",           "Bitiş Tarihi",        "To Date"),
        new("Audit.Filter.DateFormat",       "GG.AA.YYYY",          "DD.MM.YYYY"),
        new("Audit.Filter.DateFormatHelp",   "GG.AA.YYYY veya GG/AA/YYYY", "DD.MM.YYYY or DD/MM/YYYY"),
        new("Audit.Filter.User",             "Kullanıcı",           "User"),
        new("Audit.Filter.EntityType",       "Entity Tipi",         "Entity Type"),
        new("Audit.Filter.Tenant",           "Yönetim",             "Tenant"),
        new("Audit.Filter.Company",          "Site",                "Company"),
        new("Audit.Filter.Action",           "İşlem Tipi",          "Action"),
        new("Audit.Action.All",              "Tümü",                "All"),
        new("Audit.Action.Insert",           "Ekleme",              "Insert"),
        new("Audit.Action.Update",           "Güncelleme",          "Update"),
        new("Audit.Action.Delete",           "Silme",               "Delete"),
        new("Audit.Filter.Clear",            "Temizle",             "Clear"),
        new("Audit.Filter.Search",           "Ara",                 "Search"),
        new("Audit.Col.DateTime",            "Tarih/Saat",          "Date/Time"),
        new("Audit.Col.EntityType",          "Entity Tipi",         "Entity Type"),
        new("Audit.Col.EntityId",            "Entity ID",           "Entity ID"),
        new("Audit.Col.Action",              "İşlem",               "Action"),
        new("Audit.Col.User",                "Kullanıcı",           "User"),
        new("Audit.Col.Tenant",              "Yönetim",             "Tenant"),
        new("Audit.Col.Browser",             "Tarayıcı",            "Browser"),
        new("Audit.Col.Os",                  "İşletim Sistemi",     "Operating System"),
        new("Audit.Col.Endpoint",            "Endpoint",            "Endpoint"),
        new("Audit.Detail.Title",            "Audit Detayı",        "Audit Detail"),
        new("Audit.Detail.Date",             "Tarih",               "Date"),
        new("Audit.Detail.Email",            "E-posta",             "Email"),
        new("Audit.Detail.Scope",            "Kapsam",              "Scope"),
        new("Audit.Detail.Ip",               "IP",                  "IP"),
        new("Audit.Detail.Changes",          "Değişiklikler (JSON)","Changes (JSON)"),
        new("Audit.Pagination",              "Sayfa {0} / {1} — Toplam {2} kayıt", "Page {0} / {1} — Total {2} records"),
        new("Audit.LoadError",               "Yükleme hatası: {0}", "Load error: {0}"),

        // ========== Banks ==========
        new("Banks.Title",                   "Bankalar",            "Banks"),
        new("Banks.UnauthorizedSystem",      "Bu sayfa yalnız Sistem kullanıcıları için. Aktif bağlamınız Sistem değil.",
                                             "This page is for System users only. Your active context is not System."),
        new("Banks.Loading",                 "Yükleniyor...",       "Loading..."),
        new("Banks.NewButton",               "Yeni Banka",          "New Bank"),
        new("Banks.FullName",                "Tam Adı",             "Full Name"),
        new("Banks.ShortName",               "Kısa Adı",            "Short Name"),
        new("Banks.EftCode",                 "EFT Kodu",            "EFT Code"),
        new("Banks.VirtualPos",              "Sanal POS",           "Virtual POS"),
        new("Banks.CorporateCollection",     "Kurumsal Tahsilat",   "Corporate Collection"),
        new("Banks.Update",                  "Güncelle",            "Update"),
        new("Banks.Add",                     "Ekle",                "Add"),
        new("Banks.Delete.Title",            "Banka Sil",           "Delete Bank"),
        new("Banks.Delete.Confirm",          "{0} silinecek. Devam edilsin mi?", "{0} will be deleted. Continue?"),
        new("Banks.NotFound",                "Banka bulunamadı",    "Bank not found"),
        new("Banks.UpdateSuccess",           "Banka güncellendi",   "Bank updated"),
        new("Banks.AddSuccess",              "Banka eklendi",       "Bank added"),
        new("Banks.DeleteSuccess",           "Banka silindi",       "Bank deleted"),

        // ========== LookUp Tables ==========
        new("Lookup.Title",                  "LookUp Tabloları",    "Lookup Tables"),
        new("Lookup.UnauthorizedSystem",     "Bu sayfa yalnız Sistem kullanıcıları için. Aktif bağlamınız Sistem değil.",
                                             "This page is for System users only. Your active context is not System."),
        new("Lookup.Tab.Geographic",         "📍 Coğrafi Yapı",     "📍 Geographic Structure"),
        new("Lookup.Tab.Residential",        "🏠 Mesken Tipleri",   "🏠 Residential Types"),
        new("Lookup.Tab.Building",           "🏢 Yapı Tipleri",     "🏢 Building Types"),
        new("Lookup.Provinces",              "İller",               "Provinces"),
        new("Lookup.Districts",              "İlçeler",             "Districts"),
        new("Lookup.Neighborhoods",          "Mahalleler",          "Neighborhoods"),
        new("Lookup.Province.Add",           "İl Ekle",             "Add Province"),
        new("Lookup.District.Add",           "İlçe Ekle",           "Add District"),
        new("Lookup.Neighborhood.Add",       "Mahalle Ekle",        "Add Neighborhood"),
        new("Lookup.Province.Name",          "İl Adı",              "Province Name"),
        new("Lookup.Province.Plate",         "Plaka Kodu",          "Plate Code"),
        new("Lookup.District.Name",          "İlçe Adı",            "District Name"),
        new("Lookup.Neighborhood.Name",      "Mahalle Adı",         "Neighborhood Name"),
        new("Lookup.Name",                   "Ad",                  "Name"),
        new("Lookup.Description",            "Açıklama",            "Description"),
        new("Lookup.Saved",                  "Kaydedildi",          "Saved"),
        new("Lookup.Deleted",                "Silindi",             "Deleted"),
        new("Lookup.ErrorPrefix",            "Hata: {0}",           "Error: {0}"),

        // ========== Building Schema ==========
        new("BuildingSchema.Title",          "Yapı Şeması — {0}",   "Building Schema — {0}"),
        new("BuildingSchema.Unauthorized",   "Bu sayfaya erişim yetkiniz yok.", "You don't have access to this page."),
        new("BuildingSchema.LoadFailed",     "Yapı şeması yüklenemedi.", "Building schema could not be loaded."),
        new("BuildingSchema.DownloadTemplate","Şablon İndir",       "Download Template"),
        new("BuildingSchema.UploadExcel",    "Excel Yükle",         "Upload Excel"),
        new("BuildingSchema.Import.Title",   "Excel'den İçe Aktar", "Import from Excel"),
        new("BuildingSchema.SelectFile",     "Dosya Seç",           "Select File"),
        new("BuildingSchema.Upload",         "Yükle",               "Upload"),
        new("BuildingSchema.NoBlocks",       "Henüz Ada tanımlanmamış. \"Ada Ekle\" butonuyla başlayın.",
                                             "No Blocks defined yet. Start with the \"Add Block\" button."),
        new("BuildingSchema.Block.Add",      "Ada Ekle",            "Add Block"),
        new("BuildingSchema.Block.NameLabel","Ada Adı / Numarası *","Block Name / Number *"),
        new("BuildingSchema.Block.Title",    "Ada:",                "Block:"),
        new("BuildingSchema.Parcel.Add",     "Parsel Ekle",         "Add Parcel"),
        new("BuildingSchema.Parcel.NameLabel","Parsel Adı / Numarası *", "Parcel Name / Number *"),
        new("BuildingSchema.Parcel.Title",   "Parsel:",             "Parcel:"),
        new("BuildingSchema.Parcel.None",    "Parsel tanımlanmamış.", "No parcels defined."),
        new("BuildingSchema.Parcel.Count",   "{0} parsel",          "{0} parcels"),
        new("BuildingSchema.Building.Add",   "Yapı Ekle",           "Add Building"),
        new("BuildingSchema.Building.NameLabel","Yapı Adı *",       "Building Name *"),
        new("BuildingSchema.Building.MunicipalityNo","Belediye No", "Municipality No"),
        new("BuildingSchema.Building.TypeLabel","Yapı Tipi *",      "Building Type *"),
        new("BuildingSchema.Building.Title", "Yapı:",               "Building:"),
        new("BuildingSchema.Building.None",  "Yapı tanımlanmamış.", "No buildings defined."),
        new("BuildingSchema.Building.Count", "{0} yapı",            "{0} buildings"),
        new("BuildingSchema.Building.Edit",  "Yapı Düzenle",        "Edit Building"),
        new("BuildingSchema.Type.Konut",     "Konut",               "Residential"),
        new("BuildingSchema.Type.KonutIsyeri","Konut+İşyeri",       "Residential+Commercial"),
        new("BuildingSchema.Type.Avm",       "AVM",                 "Shopping Mall"),
        new("BuildingSchema.Type.Ofis",      "Ofis",                "Office"),
        new("BuildingSchema.Type.Depo",      "Depo",                "Warehouse"),
        new("BuildingSchema.Type.Diger",     "Diğer",               "Other"),
        new("BuildingSchema.Unit.Add",       "BB Ekle",             "Add Unit"),
        new("BuildingSchema.Unit.AddFull",   "Bağımsız Bölüm Ekle", "Add Unit"),
        new("BuildingSchema.Unit.Edit",      "Bağımsız Bölüm Düzenle", "Edit Unit"),
        new("BuildingSchema.Unit.NoLabel",   "BB No *",             "Unit No *"),
        new("BuildingSchema.Unit.NumberingNo","Numarataj No",       "Numbering No"),
        new("BuildingSchema.Unit.TypeLabel", "BB Tipi *",           "Unit Type *"),
        new("BuildingSchema.Unit.AreaLabel", "Metrekare (m²) *",    "Area (m²) *"),
        new("BuildingSchema.Unit.LandShare", "Arsa Payı *",         "Land Share *"),
        new("BuildingSchema.Unit.AllocatedArea","Tahsis Alanı (m²)","Allocated Area (m²)"),
        new("BuildingSchema.Unit.Floor",     "Kat",                 "Floor"),
        new("BuildingSchema.Unit.Orientation","Yön",                "Orientation"),
        new("BuildingSchema.Unit.Layout",    "Oda-Salon",           "Layout"),
        new("BuildingSchema.Unit.Count",     "{0} BB",              "{0} units"),
        new("BuildingSchema.Unit.None",      "Bağımsız bölüm tanımlanmamış.", "No units defined."),
        new("BuildingSchema.Unit.Type.Daire","Daire",               "Apartment"),
        new("BuildingSchema.Unit.Type.Ofis", "Ofis",                "Office"),
        new("BuildingSchema.Unit.Type.Dukkan","Dükkan",             "Shop"),
        new("BuildingSchema.Unit.Type.Magaza","Mağaza",             "Store"),
        new("BuildingSchema.Unit.Type.Depo", "Depo",                "Warehouse"),
        new("BuildingSchema.Unit.Type.Otopark","Otopark",           "Parking"),
        new("BuildingSchema.Unit.Type.Siginak","Sığınak",           "Shelter"),
        new("BuildingSchema.Orient.North",   "Kuzey",               "North"),
        new("BuildingSchema.Orient.South",   "Güney",               "South"),
        new("BuildingSchema.Orient.East",    "Doğu",                "East"),
        new("BuildingSchema.Orient.West",    "Batı",                "West"),
        new("BuildingSchema.Orient.NE",      "Kuzeydoğu",           "Northeast"),
        new("BuildingSchema.Orient.NW",      "Kuzeybatı",           "Northwest"),
        new("BuildingSchema.Orient.SE",      "Güneydoğu",           "Southeast"),
        new("BuildingSchema.Orient.SW",      "Güneybatı",           "Southwest"),
        new("BuildingSchema.Orient.Unknown", "Belirsiz",            "Unknown"),
        new("BuildingSchema.Layout.Studio",  "Stüdyo",              "Studio"),
        new("BuildingSchema.MoveUp",         "Yukarı Taşı",         "Move Up"),
        new("BuildingSchema.MoveDown",       "Aşağı Taşı",          "Move Down"),
        new("BuildingSchema.Confirm.Block",  "Ada '{0}' silinecek. Devam edilsin mi?", "Block '{0}' will be deleted. Continue?"),
        new("BuildingSchema.Confirm.Parcel", "Parsel '{0}' silinecek. Devam?", "Parcel '{0}' will be deleted. Continue?"),
        new("BuildingSchema.Confirm.Building","Yapı '{0}' silinecek. Devam?", "Building '{0}' will be deleted. Continue?"),
        new("BuildingSchema.Confirm.Unit",   "BB '{0}' silinecek. Devam?", "Unit '{0}' will be deleted. Continue?"),
        new("BuildingSchema.UnitAdded",      "BB eklendi.",         "Unit added."),
        new("BuildingSchema.Import.HasErrors","Excel'de hatalar var. Hata raporu indirildi.", "There are errors in the Excel. Error report downloaded."),
        new("BuildingSchema.Import.Success", "{0} bağımsız bölüm aktarıldı.", "{0} units imported."),

        // ========== Common breadcrumb ==========
        new("Breadcrumb.Home",               "Anasayfa",            "Home"),
        new("Breadcrumb.Management",         "Yönetim",             "Management"),

        // ========== Common (v0.2.10.e.4 ek) ==========
        new("Common.UnexpectedError",        "Beklenmedik hata: {0}", "Unexpected error: {0}"),
        new("Common.Discard",                "Vazgeç",              "Discard"),
        new("Common.SystemWrite.On",         "Açık",                "On"),
        new("Common.SystemWrite.Off",        "Kapalı",              "Off"),

        // ========== Page Titles ==========
        new("Tenants.List.PageTitle",        "Yönetimler — Sistem",      "Tenants — System"),
        new("Tenants.New.PageTitle",         "Yeni Yönetim — Sistem",    "New Tenant — System"),
        new("Tenants.Edit.PageTitle",        "Yönetim Düzenle — Sistem", "Edit Tenant — System"),
        new("Companies.List.PageTitle",      "Siteler — Sistem",         "Companies — System"),
        new("Companies.New.PageTitle",       "Yeni Site — CleanTenant",  "New Company — CleanTenant"),
        new("Companies.Edit.PageTitle",      "Site Düzenle — CleanTenant","Edit Company — CleanTenant"),
        new("Roles.List.PageTitle",          "Roller — Sistem",          "Roles — System"),
        new("Roles.New.PageTitle",           "Yeni Rol — Sistem",        "New Role — System"),
        new("Roles.Edit.PageTitle",          "Rol Düzenle — Sistem",     "Edit Role — System"),
        new("Banks.PageTitle",               "Bankalar — Sistem",        "Banks — System"),
        new("Audit.PageTitle",               "Audit Explorer — Sistem",  "Audit Explorer — System"),
        new("Lookup.PageTitle",              "LookUp Tabloları — Sistem","Lookup Tables — System"),

        // ========== System Area Action Errors / Tooltips ==========
        new("Tenants.New.CreateError",       "Yönetim oluşturulamadı: {0}", "Failed to create tenant: {0}"),
        new("Tenants.Edit.UpdateError",      "Güncelleme başarısız: {0}",   "Update failed: {0}"),
        new("Roles.List.BuiltInEditTooltip", "Built-in: izin yönetimi",     "Built-in: permission management"),
        new("Banks.Add.Failed",              "Ekleme başarısız: {0}",       "Failed to add: {0}"),
        new("Banks.Update.Failed",           "Güncelleme başarısız: {0}",   "Update failed: {0}"),
        new("Banks.Delete.Failed",           "Silme başarısız: {0}",        "Deletion failed: {0}"),
        new("Audit.Col.Changes",             "Değişiklikler",               "Changes"),
        new("Audit.Col.IpAddress",           "IP Adresi",                   "IP Address"),

        // ========== Tenant Area Page Titles + Errors (v0.2.10.e.5) ==========
        new("Companies.TenantList.PageTitle","Siteler — Yönetim",           "Companies — Management"),
        new("Companies.TenantList.ExportTitle","{0}-Siteler",                "{0}-Companies"),
        new("Companies.TenantNew.NoSession", "Tenant bağlamı bulunamadı.",  "No tenant context found."),
        new("Roles.TenantList.PageTitle",    "Roller — Yönetim",            "Roles — Management"),
        new("Roles.TenantNew.PageTitle",     "Yeni Rol — Yönetim",          "New Role — Management"),
        new("Roles.TenantEdit.PageTitle",    "Rol Düzenle — Yönetim",       "Edit Role — Management"),
        new("Tenants.Settings.PageTitle",    "Yönetim Ayarları",            "Tenant Settings"),
        new("Tenants.Settings.NoActiveTenant","Aktif Yönetim bulunamadı. Lütfen oturumu yenileyin.",
                                              "No active tenant found. Please refresh the session."),
        new("Tenants.Settings.SaveFailed",   "Ayarlar kaydedilemedi: {0}",  "Failed to save settings: {0}"),
        new("Tenants.Settings.SaveSuccess",  "Yönetim ayarları kaydedildi.","Tenant settings saved."),

        // ========== BuildingSchema Unit Table Headers (v0.2.10.e.5) ==========
        new("BuildingSchema.Unit.Col.No",    "No",                          "No."),
        new("BuildingSchema.Unit.Col.Type",  "Tip",                         "Type"),
        new("BuildingSchema.Unit.Col.Area",  "m²",                          "m²"),

        // ========== Auth / Pages — PageTitles & Extras (v0.2.10.e.6) ==========
        new("Login.PageTitle",                "Giriş — CleanTenant",         "Sign In — CleanTenant"),
        new("Login.Error.NoManagementScope",  "Bu kullanıcı için Management persona'sında erişilebilir bir scope yok.",
                                              "No accessible scope for this user in the Management persona."),
        new("Login.Error.IdentifierTypeUnknown","Kimlik tipi tanınamadı — geçerli bir e-posta/TCKN/VKN/telefon girin.",
                                              "Identifier type not recognized — enter a valid email/TCKN/VKN/phone."),
        new("Login.Error.TwoFactorEnrollmentRequired",
            "2FA aktivasyon gerekli. Sayfaya yönlendirilirken bir sorun oluştu — tekrar giriş yapın.",
            "2FA activation required. There was a problem with the redirect — please sign in again."),
        new("Login.Error.EnrollmentExpired",  "Enrollment süresi doldu veya iptal edildi. Lütfen tekrar giriş yapın.",
                                              "Enrollment expired or cancelled. Please sign in again."),
        new("Login.Error.EnrollmentNotVerified","Enrollment doğrulanmadan tamamlanamaz — kodu girip onaylamalısınız.",
                                              "Enrollment cannot be completed without verification — enter and confirm the code."),
        new("Login.Error.Unknown",            "Bilinmeyen hata: {0}",        "Unknown error: {0}"),

        new("TwoFactor.Challenge.PageTitle",  "2FA Doğrulama — CleanTenant", "2FA Verification — CleanTenant"),
        new("TwoFactor.Error.ChallengeNotFound","Challenge süresi doldu. Lütfen tekrar giriş yapın.",
                                              "Challenge expired. Please sign in again."),
        new("TwoFactor.Error.MethodNotAvailable","Bu yöntem hesabınızda aktif değil.",
                                              "This method is not active on your account."),
        new("TwoFactor.Error.Unknown",        "Doğrulama hatası: {0}",       "Verification error: {0}"),

        new("TwoFactor.Enroll.PageTitle",     "2FA Enrollment — CleanTenant","2FA Enrollment — CleanTenant"),
        new("TwoFactor.Enroll.StartHint",     "Başlamak için \"Enrollment başlat\" butonuna tıklayın. Bir QR kod üreteceğiz.",
                                              "Click \"Start enrollment\" to begin. We'll generate a QR code."),
        new("TwoFactor.Enroll.QrAlt",         "TOTP QR kodu",                "TOTP QR code"),

        new("TwoFactor.PreEnroll.Title",      "2FA Kurulumu",                "2FA Setup"),
        new("TwoFactor.PreEnroll.NoSession",  "Aktif bir enrollment oturumu bulunamadı (süresi dolmuş ya da iptal edilmiş olabilir).",
                                              "No active enrollment session (expired or cancelled)."),
        new("TwoFactor.PreEnroll.Loading",    "Authenticator secret üretiliyor...", "Generating authenticator secret..."),
        new("TwoFactor.PreEnroll.SystemRoleInfo",
            "{0} hesabınız System rolünde — 2FA zorunlu. Bu kurulumu tamamlayana kadar Yönetim Paneline erişemezsiniz.",
            "Your {0} account is in the System role — 2FA is required. Until you complete this setup you cannot access the Management Panel."),
        new("TwoFactor.PreEnroll.GoToPanel",  "Yönetim Paneline Geç",        "Go to Management Panel"),
        new("TwoFactor.PreEnroll.TokenValidity","Token 10 dakika geçerli.",  "Token valid for 10 minutes."),
        new("TwoFactor.PreEnroll.InvalidToken","Geçersiz token formatı.",    "Invalid token format."),

        new("Home.PageTitle",                 "Dashboard — CleanTenant",     "Dashboard — CleanTenant"),
        new("Home.Welcome.Full",
            "Hoş geldiniz. v0.2.1 Faz 1 başlangıç sürümü — gerçek veriler v0.2.2'de auth devreye girdiğinde gelir.",
            "Welcome. v0.2.1 Phase 1 initial version — real data arrives when auth is enabled in v0.2.2."),

        new("About.PageTitle",                "Hakkında — CleanTenant",      "About — CleanTenant"),
        new("About.PhaseZero.Title",          "Faz 0 Çıktıları",             "Phase 0 Deliverables"),

        new("NotFound.PageTitle",             "404 — Sayfa Bulunamadı",      "404 — Page Not Found"),

        new("Settings.Theme.PageTitle",       "Tema Ayarları — CleanTenant", "Theme Settings — CleanTenant"),
        new("Settings.Language.PageTitle",    "Dil Ayarları — CleanTenant",  "Language Settings — CleanTenant"),

        // ========== Localization Manage Page (v0.2.10.g) ==========
        new("LocalizationManage.PageTitle",            "Dil Kaynakları — CleanTenant",                  "Localization Resources — CleanTenant"),
        new("LocalizationManage.Title",                "Dil Kaynakları Yönetimi",                       "Localization Resources Management"),
        new("LocalizationManage.UnauthorizedSystem",   "Bu sayfaya sadece Sistem operatörleri erişebilir.", "This page is only accessible to System operators."),

        new("LocalizationManage.Filter.Title",             "Filtreler",                                 "Filters"),
        new("LocalizationManage.Filter.Culture",           "Kültür",                                    "Culture"),
        new("LocalizationManage.Filter.Search",            "Ara (anahtar veya değer)",                  "Search (key or value)"),
        new("LocalizationManage.Filter.SearchPlaceholder", "Örn. Roles.New veya Hoşgeldin",             "e.g. Roles.New or Welcome"),
        new("LocalizationManage.Filter.OnlyMachine",       "Yalnız makine çevirileri",                  "Only machine translations"),
        new("LocalizationManage.Filter.SearchButton",      "Ara",                                       "Search"),
        new("LocalizationManage.Filter.Clear",             "Temizle",                                   "Clear"),

        new("LocalizationManage.Col.Key",          "Anahtar",                                           "Key"),
        new("LocalizationManage.Col.Value",        "Değer",                                             "Value"),
        new("LocalizationManage.Col.MachineFlag",  "Makine",                                            "Machine"),
        new("LocalizationManage.Col.UpdatedAt",    "Güncellenme",                                       "Updated"),
        new("LocalizationManage.Col.Edit",         "İşlem",                                             "Action"),

        new("LocalizationManage.Drawer.Title",         "Çeviri Düzenle",                                "Edit Translation"),
        new("LocalizationManage.Drawer.Key",           "Anahtar",                                       "Key"),
        new("LocalizationManage.Drawer.Culture",       "Kültür",                                        "Culture"),
        new("LocalizationManage.Drawer.CurrentValue",  "Mevcut Değer",                                  "Current Value"),
        new("LocalizationManage.Drawer.NewValue",      "Yeni Değer",                                    "New Value"),
        new("LocalizationManage.Drawer.SaveButton",    "Kaydet",                                        "Save"),
        new("LocalizationManage.Drawer.CancelButton",  "İptal",                                         "Cancel"),

        new("LocalizationManage.Pagination",   "Sayfa {0} / {1} (toplam {2} kayıt)",                    "Page {0} / {1} (total {2} records)"),
        new("LocalizationManage.MachineYes",   "Otomatik",                                              "Auto"),
        new("LocalizationManage.LoadError",    "Kayıtlar yüklenemedi: {0}",                             "Failed to load records: {0}"),
        new("LocalizationManage.SaveSuccess",  "Kayıt güncellendi.",                                    "Record updated."),
        new("LocalizationManage.SaveError",    "Kayıt güncellenemedi: {0}",                             "Failed to update record: {0}"),
    ];
}
